name: psp
channels:
  # - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pytest
  - gdal
  - rasterio
  - pip
  - geopandas
  - pandas
  - ipykernel
  - black
  - xarray
  - netcdf4
  - rioxarray
  - dask
  - bottleneck
  - jupyter
  - zarr
  - yaml
