[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "polsarpro"
version = "2025.10.0"
description = "Re-implementation of selected PolSARpro functions in Python, following the scientific recommendations of PolInSAR 2021."
dependencies = ["python==3.12.12", "pytest==9.0.1", "gdal==3.10.3", "rasterio==1.4.3", "pip==25.3", "geopandas==1.1.1", "pandas==2.3.3", "ipykernel==7.1.0", "black==25.1.0", "xarray==2025.11.0", "netcdf4==1.7.3", "rioxarray==0.20.0", "dask==2025.11.0", "bottleneck==1.6.0", "jupyter==1.1.1", "zarr==3.1.5", "yaml==0.2.5"]
[[project.authors]]
name = "Olivier D'Hondt"
email = "dhondt.olivier@gmail.com"

[tool.setuptools]
packages = [ "polsarpro"]
include-package-data = true
